name: Build ROM
on: [push]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v4
        - name: Build
          run: |
            sudo apt-get update
            sudo apt-get install -y binutils-arm-none-eabi gcc-arm-none-eabi libpng-dev make
            make

